/**
 * Forwarded-bid intake addressing.
 *
 * Contractors forward invitations to bid to `estimates@bids.mobiestimates.com`.
 * Forwarding is the highest-adoption intake channel in construction —
 * estimators already forward ITBs internally, so it costs a new contractor
 * nothing to learn and works from a phone on a job site, which uploading a plan
 * set does not.
 *
 * One shared mailbox can't tell us WHICH client forwarded, so there are two
 * addresses and a routing order:
 *
 *   1. `estimates+{intake_slug}@…` — the per-company address shown in the
 *      portal. The slug is unguessable, so this routes deterministically no
 *      matter who forwards it (an assistant, a phone's personal account, a GC's
 *      own mail system re-sending it).
 *   2. `estimates@…` — the plain shared address. Routed by matching the SENDER
 *      to a member of a company, which is why the tagged form is what we print:
 *      the plain one silently fails for anyone forwarding from an address that
 *      isn't on the account.
 *
 * Anything we can't place is held for staff triage rather than dropped. See
 * src/lib/inbound-intake-server.ts.
 *
 * Pure + env-only: safe to import from server and client components alike.
 */

/**
 * Intake receives on a SUBDOMAIN, not the root domain.
 *
 * Enabling receiving points the domain's MX at Resend, and Resend receives
 * every address on that domain — it is a webhook target, not a mailbox host.
 * `mobiestimates.com` already has MX records for the company's real mailboxes
 * (Private Email), so pointing the root at Resend would not split traffic, it
 * would take over the owner's own mail and leave nowhere to read it. Resend
 * documents the same recommendation. Sending is unaffected: SPF/DKIM are TXT
 * records and do not conflict with MX.
 */
const DEFAULT_INTAKE_EMAIL_DOMAIN = "bids.mobiestimates.com";
const DEFAULT_INTAKE_MAILBOX = "estimates";

/** Hostname shape: labels of [a-z0-9-] separated by dots, at least two labels. */
const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;
/** Mailbox (local part) shape, deliberately narrower than RFC 5321 allows. */
const MAILBOX_RE = /^[a-z0-9]([a-z0-9._-]*[a-z0-9])?$/;

/**
 * The receiving domain configured in Resend (its MX record points at Resend, and
 * every address on it is delivered to our webhook). Falls back to the canonical
 * receiving subdomain if unset or malformed, so a bad env var can never render a
 * broken address to a customer.
 */
export function intakeEmailDomain(): string {
  const raw = process.env.NEXT_PUBLIC_INTAKE_EMAIL_DOMAIN?.trim().toLowerCase();
  if (!raw || !DOMAIN_RE.test(raw)) return DEFAULT_INTAKE_EMAIL_DOMAIN;
  return raw;
}

/** Local part of the shared intake mailbox (`estimates` in estimates@…). */
export function intakeMailbox(): string {
  const raw = process.env.NEXT_PUBLIC_INTAKE_EMAIL_MAILBOX?.trim().toLowerCase();
  if (!raw || !MAILBOX_RE.test(raw)) return DEFAULT_INTAKE_MAILBOX;
  return raw;
}

/**
 * Slug shape. Slugs are generated by the database (migration 0036) as
 * `{stem}-{random hex}`, and requiring that trailing hex run is what keeps a
 * plain mailbox name like `estimates` — or any other address that happens to
 * arrive on the domain — from being mistaken for a company alias.
 */
const SLUG_RE = /^[a-z0-9][a-z0-9-]*-[0-9a-f]{6,}$/;

export function isValidIntakeSlug(slug: string | null | undefined): boolean {
  return typeof slug === "string" && slug.length >= 8 && slug.length <= 64 && SLUG_RE.test(slug);
}

/** The plain shared intake address. */
export function sharedIntakeAddress(): string {
  return `${intakeMailbox()}@${intakeEmailDomain()}`;
}

/**
 * The per-company address to print in the portal, or null if the slug is
 * missing/invalid. Returns null rather than a guessed address: showing a
 * contractor an address that doesn't route would silently drop the bid documents
 * they forward to it.
 */
export function intakeAddressForSlug(slug: string | null | undefined): string | null {
  if (!isValidIntakeSlug(slug)) return null;
  return `${intakeMailbox()}+${slug}@${intakeEmailDomain()}`;
}

/**
 * Reduce an address to a comparable form: strip a display name, angle brackets,
 * and surrounding whitespace, then lowercase. Does NOT strip +tags — two
 * addresses that differ only by tag are different mailboxes for sender matching.
 */
export function normalizeEmailAddress(raw: string | null | undefined): string {
  if (!raw) return "";
  const angled = raw.match(/<([^>]+)>/);
  return (angled ? angled[1] : raw).trim().toLowerCase();
}

/** Display name from a `Name <addr>` header value, if present. */
export function displayNameFromAddress(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const m = raw.match(/^\s*"?([^"<]+?)"?\s*<[^>]+>\s*$/);
  const name = m?.[1]?.trim();
  return name ? name : null;
}

/** Split a normalized address into local part and domain, or null. */
function splitAddress(address: string | null | undefined): { local: string; domain: string } | null {
  const normalized = normalizeEmailAddress(address);
  const at = normalized.lastIndexOf("@");
  if (at <= 0 || at === normalized.length - 1) return null;
  return { local: normalized.slice(0, at), domain: normalized.slice(at + 1) };
}

/** Whether an address is on our receiving domain at all. */
export function isIntakeDomainAddress(
  address: string | null | undefined,
  domain: string = intakeEmailDomain(),
): boolean {
  return splitAddress(address)?.domain === domain.toLowerCase();
}

/**
 * Extract a company's intake slug from a recipient address.
 *
 * Accepts both `estimates+{slug}@domain` and the bare `{slug}@domain`. The base
 * before `+` is deliberately not checked against the configured mailbox: the
 * slug itself is the unguessable part, so being lenient here only improves
 * routing and cannot deliver documents to the wrong tenant.
 */
export function intakeSlugFromAddress(
  address: string | null | undefined,
  domain: string = intakeEmailDomain(),
): string | null {
  const parts = splitAddress(address);
  if (!parts || parts.domain !== domain.toLowerCase()) return null;

  const plus = parts.local.indexOf("+");
  const candidate = plus >= 0 ? parts.local.slice(plus + 1) : parts.local;
  return isValidIntakeSlug(candidate) ? candidate : null;
}

/** Whether an address is the plain shared mailbox, with no company tag. */
export function isSharedIntakeAddress(
  address: string | null | undefined,
  domain: string = intakeEmailDomain(),
  mailbox: string = intakeMailbox(),
): boolean {
  const parts = splitAddress(address);
  if (!parts || parts.domain !== domain.toLowerCase()) return false;
  return parts.local === mailbox.toLowerCase();
}

/**
 * Find the company tag among every recipient of a forwarded message. A
 * contractor forwarding to us will often also cc their own team, so the
 * recipient list holds several addresses of which only one is ours.
 */
export function findIntakeSlug(
  recipients: readonly (string | null | undefined)[],
  domain: string = intakeEmailDomain(),
): string | null {
  for (const recipient of recipients) {
    const slug = intakeSlugFromAddress(recipient, domain);
    if (slug) return slug;
  }
  return null;
}

/** The first recipient that is on our receiving domain, if any. */
export function findIntakeRecipient(
  recipients: readonly (string | null | undefined)[],
  domain: string = intakeEmailDomain(),
): string | null {
  for (const recipient of recipients) {
    if (isIntakeDomainAddress(recipient, domain)) return normalizeEmailAddress(recipient);
  }
  return null;
}

/** Storage key prefix for a captured forward's documents, inside 'project-files'.
 *  Keeps {company_id} first so the existing bucket RLS policy applies unchanged. */
export function inboundIntakeStorageFolder(companyId: string, messageId: string): string {
  return `${companyId}/inbound/${messageId}`;
}
