/**
 * Per-company forwarded-bid intake addresses.
 *
 * Every company gets an unguessable address, {intake_slug}@{intake domain},
 * that it can forward invitations to bid to. Forwarding is the highest-adoption
 * intake channel in construction — estimators already forward ITBs internally,
 * so it costs a new contractor nothing to learn and works from a phone on a job
 * site, which uploading a plan set does not.
 *
 * Pure + env-only: safe to import from server and client components alike.
 */

const DEFAULT_INTAKE_EMAIL_DOMAIN = "bids.mobiestimates.com";

/** Hostname shape: labels of [a-z0-9-] separated by dots, at least two labels. */
const DOMAIN_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$/;

/**
 * The receiving domain configured in Resend (MX records point at it, and the
 * catch-all forwards every address to our webhook). Falls back to the canonical
 * production domain if unset or malformed, so a bad env var can never render a
 * broken address to a customer.
 */
export function intakeEmailDomain(): string {
  const raw = process.env.NEXT_PUBLIC_INTAKE_EMAIL_DOMAIN?.trim().toLowerCase();
  if (!raw || !DOMAIN_RE.test(raw)) return DEFAULT_INTAKE_EMAIL_DOMAIN;
  return raw;
}

/** Slugs are generated by the DB (see migration 0036); this only guards rendering. */
const SLUG_RE = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;

export function isValidIntakeSlug(slug: string | null | undefined): boolean {
  return typeof slug === "string" && slug.length >= 3 && slug.length <= 64 && SLUG_RE.test(slug);
}

/** Full forwarding address for a company, or null if the slug is missing/invalid. */
export function intakeAddressForSlug(slug: string | null | undefined): string | null {
  if (!isValidIntakeSlug(slug)) return null;
  return `${slug}@${intakeEmailDomain()}`;
}

/**
 * Reduce an address to a comparable form: strip a display name, angle brackets,
 * and surrounding whitespace, then lowercase. Does NOT strip +tags — two
 * addresses that differ only by tag are different mailboxes for sender matching.
 */
export function normalizeEmailAddress(raw: string | null | undefined): string {
  if (!raw) return "";
  const angled = raw.match(/<([^>]+)>/);
  return (angled ? angled[1] : raw).trim().toLowerCase();
}

/** Display name from a `Name <addr>` header value, if present. */
export function displayNameFromAddress(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const m = raw.match(/^\s*"?([^"<]+?)"?\s*<[^>]+>\s*$/);
  const name = m?.[1]?.trim();
  return name ? name : null;
}

/**
 * Extract the intake slug from a recipient address, or null when the address is
 * not on our receiving domain. A `+tag` suffix is ignored so a contractor's own
 * mail rules (which sometimes append tags) still resolve to the right company.
 */
export function intakeSlugFromAddress(
  address: string | null | undefined,
  domain: string = intakeEmailDomain(),
): string | null {
  const normalized = normalizeEmailAddress(address);
  const at = normalized.lastIndexOf("@");
  if (at <= 0) return null;
  if (normalized.slice(at + 1) !== domain.toLowerCase()) return null;

  const local = normalized.slice(0, at).split("+")[0];
  return isValidIntakeSlug(local) ? local : null;
}

/**
 * Find the intake slug among every recipient of a forwarded message. A contractor
 * forwarding to us will often also cc their own team, so `to` can hold several
 * addresses of which only one is ours.
 */
export function findIntakeSlug(
  recipients: readonly (string | null | undefined)[],
  domain: string = intakeEmailDomain(),
): string | null {
  for (const recipient of recipients) {
    const slug = intakeSlugFromAddress(recipient, domain);
    if (slug) return slug;
  }
  return null;
}

/** Storage key prefix for a captured forward's documents, inside 'project-files'.
 *  Keeps {company_id} first so the existing bucket RLS policy applies unchanged. */
export function inboundIntakeStorageFolder(companyId: string, messageId: string): string {
  return `${companyId}/inbound/${messageId}`;
}
