"""Generic-Lane Scope Candidate Creation v1.

This turns census-detected coverage rows into one pending generic scope item per
trade. It is intentionally conservative: quantity remains unknown, pricing is not
performed, and every item carries assumptions/blockers so downstream automation
cannot mistake it for a final priced estimate.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any
from uuid import UUID, uuid4

from app.coverage_db import list_coverage_rows, update_coverage_row
from app.estimating.quantities import QuantityBasis
from app.extraction.schemas import ExtractionStatus, ReviewStatus
from app.extraction_db import (
    append_review_event,
    claim_extraction_run,
    insert_evidence,
    insert_scope_item,
    list_scope_items,
    update_run,
)

GENERIC_MODULE_VERSION = "0.1.0"
GENERIC_SCHEMA_VERSION = "1.0"
GENERIC_PROVIDER = "deterministic_generic_lane"
GENERIC_PROMPT_VERSION = "generic-scope-v1"

TERMINAL_SKIP_DISPOSITIONS = {
    "excluded_by_customer",
    "excluded_by_mobi",
    "not_applicable",
    "blocked_needs_info",
    "blocked_needs_source_data",
}


def _first_evidence_ref(row: dict[str, Any]) -> dict[str, Any] | None:
    """Pick the best sheet-backed evidence ref for a generic scope item.

    Prefer actual extracted sheet/index text before fallback source pointers. Some
    census rows contain multiple refs where the first item is a verified page
    pointer without a quote and a later item carries a real ``text_quote``. Using
    the quoted ref first improves staff evidence coverage without fabricating
    evidence: every returned ref still has a sheet id and PDF page number. If no
    real text quote exists, keep verified sheet pointers ahead of rule-label
    ``reason`` fields so generated detection labels are not promoted over safer
    source pointers.
    """
    refs = [
        ref for ref in (row.get("evidence_refs") or [])
        if ref.get("sheet_id") and ref.get("pdf_page_number")
    ]
    for ref in refs:
        if ref.get("text_quote"):
            return ref
    for ref in refs:
        if ref.get("verified_sheet_number") or ref.get("verified_sheet_title"):
            return ref
    for ref in refs:
        if ref.get("reason"):
            return ref
    return None


def _existing_active_scope_count(project_id: UUID, trade_code: str) -> int:
    items, _ = list_scope_items(
        project_id,
        filters={"trade_code": trade_code},
        limit=200,
        offset=0,
    )
    return sum(1 for item in items if item.get("review_status") != ReviewStatus.REJECTED.value)


def _run_for_trade(project_id: UUID, trade_code: str) -> dict[str, Any]:
    outcome, run = claim_extraction_run(
        project_id=project_id,
        trade_code=trade_code,
        provider=GENERIC_PROVIDER,
        model=None,
        prompt_version=GENERIC_PROMPT_VERSION,
        provider_schema_version="1.0",
        trade_schema_version=GENERIC_SCHEMA_VERSION,
        force=False,
        dry_run=False,
    )
    if outcome == "created":
        update_run(UUID(run["id"]), status=ExtractionStatus.RUNNING.value)
        updated = update_run(
            UUID(run["id"]),
            status=ExtractionStatus.COMPLETED.value,
            completed_at=datetime.now(timezone.utc).isoformat(),
            input_sheet_count=1,
            processed_sheet_count=1,
            blocked_sheet_count=0,
            failed_sheet_count=0,
            candidate_count=1,
        )
        assert updated is not None
        return updated
    return run


def _scope_payload(project_id: UUID, run: dict[str, Any], row: dict[str, Any]) -> dict[str, Any]:
    trade_name = row.get("trade_name") or row["trade_code"]
    assumptions = [
        {"text": "Generated by Generic-Lane Scope Candidate v1 from trade coverage evidence."},
        {"text": "Quantity, assemblies, production rates, and pricing are not determined in this step."},
        {"text": "Downstream automation must refine, price, exclude, quote, or ask the customer before delivery."},
    ]
    blockers = [
        {"code": "missing_quantity", "message": "Generic scope candidate has no quantity yet."},
        {"code": "missing_pricing_basis", "message": "Generic scope candidate has no pricing basis yet."},
    ]
    return {
        "id": str(uuid4()),
        "project_id": str(project_id),
        "extraction_run_id": run["id"],
        "trade_code": row["trade_code"],
        "trade_module_version": GENERIC_MODULE_VERSION,
        "trade_schema_version": GENERIC_SCHEMA_VERSION,
        "category_code": "generic_scope",
        "description": f"{trade_name} scope detected by automatic trade census",
        "location": None,
        "specification_section": ", ".join(row.get("csi_divisions") or []) or None,
        "assembly_designation": None,
        "material_or_substrate": None,
        "existing_condition": None,
        "proposed_work": f"Carry {trade_name} as generic all-trade scope pending downstream takeoff/pricing.",
        "quantity": None,
        "unit": None,
        "quantity_basis": QuantityBasis.UNKNOWN.value,
        "raw_quantity_inputs": {
            "source": "trade_coverage_matrix",
            "coverage_row_id": row["id"],
        },
        "extraction_confidence": row.get("confidence"),
        "conflict_status": "blocking",
        "review_status": ReviewStatus.BLOCKED.value,
        "blocking_issues": blockers,
        "assumptions": assumptions,
        "exclusions": [],
        "trade_data": {
            "source_trade_code": row["trade_code"],
            "source_trade_name": trade_name,
            "pricing_method": "blocked",
            "quantity_method": "blocked",
            "confidence_note": row.get("basis_note"),
            "generic_lane": "general_trade",
        },
        "original_provider_candidate": {
            "source": "generic_lane_scope_v1",
            "coverage_row_id": row["id"],
            "detected_from": row.get("detected_from") or [],
        },
        "calculation_id": None,
        "calculation_version": None,
        "reviewer_notes": None,
    }


def _insert_evidence_for_scope(project_id: UUID, scope_item: dict[str, Any], row: dict[str, Any]) -> int:
    ref = _first_evidence_ref(row)
    if ref is None:
        return 0
    insert_evidence({
        "id": str(uuid4()),
        "scope_item_id": scope_item["id"],
        "project_id": str(project_id),
        "sheet_id": ref["sheet_id"],
        "pdf_page_number": ref["pdf_page_number"],
        "verified_sheet_number": ref.get("verified_sheet_number") or ref.get("verified_sheet_title") or "unverified",
        "evidence_type": "other",
        "description": f"Trade census signal for {row['trade_name']}",
        "extracted_text_quote": ref.get("text_quote") or ref.get("reason"),
        "source_artifact_ref": None,
        "provider_confidence": row.get("confidence"),
        "requires_human_verification": True,
    })
    return 1


def draft_generic_scope_candidates(project_id: UUID) -> dict[str, Any]:
    rows = list_coverage_rows(project_id)
    created: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []

    for row in rows:
        disposition = row.get("disposition") or "undispositioned"
        if disposition in TERMINAL_SKIP_DISPOSITIONS:
            skipped.append({"trade_code": row["trade_code"], "reason": f"disposition:{disposition}"})
            continue
        if _existing_active_scope_count(project_id, row["trade_code"]) > 0:
            skipped.append({"trade_code": row["trade_code"], "reason": "active_scope_exists"})
            continue

        run = _run_for_trade(project_id, row["trade_code"])
        scope_item = insert_scope_item(_scope_payload(project_id, run, row))
        evidence_count = _insert_evidence_for_scope(project_id, scope_item, row)
        append_review_event({
            "project_id": str(project_id),
            "scope_item_id": scope_item["id"],
            "trade_code": row["trade_code"],
            "action": "generic_scope_drafted",
            "previous_state": None,
            "new_state": scope_item["review_status"],
            "reviewer_id": "system",
            "reviewer_notes": "Generated by Generic-Lane Scope Candidate v1.",
        })
        update_coverage_row(
            project_id,
            UUID(row["id"]),
            {
                "disposition": "included_generic",
                "status": "ready",
                "basis_note": row.get("basis_note") or "Generic lane scope candidate created.",
            },
        )
        created.append({**scope_item, "evidence_count": evidence_count})

    return {
        "project_id": str(project_id),
        "created_count": len(created),
        "skipped_count": len(skipped),
        "created": created,
        "skipped": skipped,
    }
